
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Runs on every app startup. Idempotent.
 * - Establishes practice identity if not yet done (first run)
 * - Starts eval period if no license events exist (first run)
 * - Detects clock rollback (appends ClockRollbackDetected if detected)
 * - Records a successful validation timestamp
 * - Rebuilds projections and returns current license status
 */
async startupLicenseCheck() : Promise<Result<LicenseStatusDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("startup_license_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current license status (rebuilds projection with current time).
 */
async getLicenseStatus() : Promise<Result<LicenseStatusDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_license_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current practice_id, or None if identity not yet established.
 */
async getPracticeId() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_practice_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Activates a paid license key. Validates the key, checks practice_id match, appends LicenseIssued.
 */
async activateLicense(licenseKey: string) : Promise<Result<LicenseStatusDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_license", { licenseKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePracticeDetails(name: string, phone: string | null, email: string | null, website: string | null, addressLine1: string | null, addressLine2: string | null, cityTown: string | null, subdivision: string | null, country: string | null) : Promise<Result<PracticeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_practice_details", { name, phone, email, website, addressLine1, addressLine2, cityTown, subdivision, country }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPractice() : Promise<Result<PracticeDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_practice") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createOffice(name: string, chairCount: number) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_office", { name, chairCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameOffice(officeId: string, newName: string) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_office", { officeId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateOfficeChairCount(officeId: string, newChairCount: number) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_office_chair_count", { officeId, newChairCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOfficeHours(officeId: string, dayOfWeek: string, openTime: string, closeTime: string) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_office_hours", { officeId, dayOfWeek, openTime, closeTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeOfficeDay(officeId: string, dayOfWeek: string) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_office_day", { officeId, dayOfWeek }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOfficeAddress(officeId: string, addressLine1: string | null, addressLine2: string | null, cityTown: string | null, subdivision: string | null, country: string | null) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_office_address", { officeId, addressLine1, addressLine2, cityTown, subdivision, country }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveOffice(officeId: string) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_office", { officeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOffices() : Promise<Result<OfficeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_offices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOffice(officeId: string) : Promise<Result<OfficeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_office", { officeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerProvider(name: string, providerType: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_provider", { name, providerType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameProvider(providerId: string, newName: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_provider", { providerId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeProviderType(providerId: string, newProviderType: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_provider_type", { providerId, newProviderType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assignProviderToOffice(providerId: string, officeId: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_provider_to_office", { providerId, officeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProviderFromOffice(providerId: string, officeId: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_provider_from_office", { providerId, officeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProviderAvailability(providerId: string, officeId: string, dayOfWeek: string, startTime: string, endTime: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_availability", { providerId, officeId, dayOfWeek, startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearProviderAvailability(providerId: string, officeId: string, dayOfWeek: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_provider_availability", { providerId, officeId, dayOfWeek }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProviderException(providerId: string, startDate: string, endDate: string, reason: string | null) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_exception", { providerId, startDate, endDate, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProviderException(providerId: string, startDate: string, endDate: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_provider_exception", { providerId, startDate, endDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveProvider(providerId: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unarchiveProvider(providerId: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviders() : Promise<Result<ProviderDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProvider(providerId: string) : Promise<Result<ProviderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async defineProcedureType(name: string, category: string, defaultDurationMinutes: number) : Promise<Result<ProcedureTypeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("define_procedure_type", { name, category, defaultDurationMinutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProcedureType(id: string, name: string | null, category: string | null, defaultDurationMinutes: number | null) : Promise<Result<ProcedureTypeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_procedure_type", { id, name, category, defaultDurationMinutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deactivateProcedureType(id: string) : Promise<Result<ProcedureTypeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deactivate_procedure_type", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reactivateProcedureType(id: string) : Promise<Result<ProcedureTypeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reactivate_procedure_type", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedDefaultProcedureTypes() : Promise<Result<ProcedureTypeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_default_procedure_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProcedureTypes() : Promise<Result<ProcedureTypeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_procedure_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerPatient(firstName: string, lastName: string, phone: string | null, email: string | null, preferredContactChannel: string | null, preferredOfficeId: string | null, dateOfBirth: string | null, registeredBy: string) : Promise<Result<RegisterPatientResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_patient", { firstName, lastName, phone, email, preferredContactChannel, preferredOfficeId, dateOfBirth, registeredBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePatientDemographics(patientId: string, firstName: string, lastName: string, dateOfBirth: string | null, addressLine1: string | null, cityTown: string | null, subdivision: string | null, country: string | null, updatedBy: string) : Promise<Result<PatientDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_patient_demographics", { patientId, firstName, lastName, dateOfBirth, addressLine1, cityTown, subdivision, country, updatedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePatientContactInfo(patientId: string, phone: string | null, email: string | null, preferredContactChannel: string | null, updatedBy: string) : Promise<Result<PatientDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_patient_contact_info", { patientId, phone, email, preferredContactChannel, updatedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPatientNote(patientId: string, text: string, recordedBy: string) : Promise<Result<PatientNoteDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_patient_note", { patientId, text, recordedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archivePatient(patientId: string, archivedBy: string) : Promise<Result<PatientDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_patient", { patientId, archivedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unarchivePatient(patientId: string, unarchivedBy: string) : Promise<Result<PatientDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_patient", { patientId, unarchivedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPatients(namePrefix: string | null, phoneFragment: string | null, preferredOfficeId: string | null, includeArchived: boolean) : Promise<Result<PatientDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_patients", { namePrefix, phoneFragment, preferredOfficeId, includeArchived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPatient(patientId: string) : Promise<Result<PatientWithNotesDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_patient", { patientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * First-run bootstrap: first person claims the PracticeManager role.
 * Rejected if any active PracticeManager already exists.
 */
async claimPracticeManagerRole(name: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_practice_manager_role", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a new staff member. Requires at least one active PracticeManager.
 */
async registerStaffMember(name: string, phone: string | null, email: string | null, preferredContactChannel: string | null, initialRole: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_staff_member", { name, phone, email, preferredContactChannel, initialRole }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assignRole(staffMemberId: string, role: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_role", { staffMemberId, role }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeRole(staffMemberId: string, role: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_role", { staffMemberId, role }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPin(staffMemberId: string, newPin: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pin", { staffMemberId, newPin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePin(staffMemberId: string, currentPin: string, newPin: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_pin", { staffMemberId, currentPin, newPin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Practice Manager resets another staff member's PIN (forgotten PIN recovery).
 */
async resetPin(staffMemberId: string, resetByStaffMemberId: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_pin", { staffMemberId, resetByStaffMemberId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveStaffMember(staffMemberId: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_staff_member", { staffMemberId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unarchiveStaffMember(staffMemberId: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_staff_member", { staffMemberId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify a PIN without creating any domain event. Returns true if correct.
 * This is a session concern — no event is emitted.
 */
async verifyStaffPin(staffMemberId: string, pin: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_staff_pin", { staffMemberId, pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listStaffMembers() : Promise<Result<StaffMemberDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_staff_members") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStaffMemberDto(staffMemberId: string) : Promise<Result<StaffMemberDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_staff_member_dto", { staffMemberId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Staff Management setup step: complete when at least one active PM has a PIN.
 */
async getStaffSetupStatus() : Promise<Result<StaffSetupStatusDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_staff_setup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query whether a provider is available at an office on a given date and time.
 * 
 * date: "YYYY-MM-DD", time: "HH:MM"
 * Returns {available, reason} where reason is null when available is true.
 */
async queryProviderAvailability(providerId: string, officeId: string, date: string, time: string) : Promise<Result<ProviderAvailabilityResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_provider_availability", { providerId, officeId, date, time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all providers working at an office on a given date.
 * 
 * date: "YYYY-MM-DD". Returns empty list if date is more than 90 days from today.
 * Each entry includes provider_id, provider_name, start_time, end_time (availability window for the day).
 */
async getOfficeProviderSchedule(officeId: string, date: string) : Promise<Result<ProviderScheduleEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_office_provider_schedule", { officeId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bookAppointment(officeId: string, patientId: string, procedureTypeId: string, providerId: string, startTime: string, durationMinutes: number | null, bookedBy: string) : Promise<Result<BookAppointmentResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("book_appointment", { officeId, patientId, procedureTypeId, providerId, startTime, durationMinutes, bookedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rescheduleAppointment(appointmentId: string, newOfficeId: string, newProviderId: string, newStartTime: string, newDurationMinutes: number | null, rescheduledBy: string) : Promise<Result<RescheduleAppointmentResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reschedule_appointment", { appointmentId, newOfficeId, newProviderId, newStartTime, newDurationMinutes, rescheduledBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAppointment(appointmentId: string, cancelledBy: string, reason: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_appointment", { appointmentId, cancelledBy, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeAppointment(appointmentId: string, completedBy: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_appointment", { appointmentId, completedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAppointmentNoShow(appointmentId: string, recordedBy: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_appointment_no_show", { appointmentId, recordedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAppointmentNote(appointmentId: string, text: string, recordedBy: string) : Promise<Result<AppointmentNoteDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_appointment_note", { appointmentId, text, recordedBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSchedule(officeId: string, date: string) : Promise<Result<AppointmentDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedule", { officeId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppointment(appointmentId: string) : Promise<Result<AppointmentWithNotesDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_appointment", { appointmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProviderSchedule(providerId: string, startDate: string, endDate: string) : Promise<Result<AppointmentDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_provider_schedule", { providerId, startDate, endDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTomorrowsCallList(officeId: string, date: string) : Promise<Result<CallListEntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tomorrows_call_list", { officeId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedDemoData() : Promise<Result<SeedSummaryDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_demo_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveDemoData() : Promise<Result<ArchiveSummaryDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_demo_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppointmentDto = { appointment_id: string; office_id: string; patient_id: string; patient_name: string; patient_phone: string | null; procedure_type_id: string; procedure_name: string; procedure_category: string; provider_id: string; provider_name: string; start_time: string; end_time: string; duration_minutes: number; status: string; rescheduled_to_id: string | null; rescheduled_from_id: string | null; booked_by: string }
export type AppointmentNoteDto = { note_id: string; appointment_id: string; text: string; recorded_by: string; recorded_at: string }
export type AppointmentWithNotesDto = { appointment: AppointmentDto; notes: AppointmentNoteDto[] }
export type ArchiveSummaryDto = { patients_archived: number; providers_archived: number; staff_archived: number }
export type AvailabilityExceptionDto = { start_date: string; end_date: string; reason: string | null }
export type AvailabilityWindowDto = { office_id: string; day_of_week: string; start_time: string; end_time: string }
export type BookAppointmentResult = { appointment_id: string }
export type CallListEntryDto = { appointment_id: string; office_id: string; patient_name: string; patient_phone: string | null; patient_email: string | null; preferred_contact_channel: string | null; procedure_name: string; provider_name: string; start_time: string }
/**
 * Overall license status returned to the frontend.
 * All datetime fields are ISO 8601 strings — DateTime<Utc> does not impl specta::Type.
 */
export type LicenseStatusDto = { overall_validity: string; license_type: string | null; eval_expires_at: string | null; modules: ModuleStatusDto[]; last_validated_at: string | null }
/**
 * Per-module status returned to the frontend.
 */
export type ModuleStatusDto = { module_name: string; status: string; expires_at: string; grace_period_days: number; grace_expires_at: string | null; days_remaining: number | null }
export type OfficeDto = { id: string; name: string; chair_count: number; hours: OfficeHoursDto[]; archived: boolean; address_line_1: string | null; address_line_2: string | null; city_town: string | null; subdivision: string | null; country: string | null }
export type OfficeHoursDto = { day_of_week: string; open_time: string; close_time: string }
export type PatientDto = { patient_id: string; first_name: string; last_name: string; full_name_display: string; phone: string | null; email: string | null; preferred_contact_channel: string | null; preferred_office_id: string | null; date_of_birth: string | null; address_line_1: string | null; city_town: string | null; subdivision: string | null; country: string | null; registered_by: string; registered_at: string; archived: boolean }
export type PatientNoteDto = { note_id: string; patient_id: string; text: string; recorded_by: string; recorded_at: string }
/**
 * Returned from get_patient — includes the patient plus their notes.
 */
export type PatientWithNotesDto = { patient: PatientDto; notes: PatientNoteDto[] }
export type PracticeDto = { name: string; phone: string | null; email: string | null; website: string | null; address_line_1: string | null; address_line_2: string | null; city_town: string | null; subdivision: string | null; country: string | null }
export type ProcedureTypeDto = { id: string; name: string; category: string; default_duration_minutes: number; is_active: boolean }
export type ProviderAvailabilityResult = { available: boolean; reason: string | null }
export type ProviderDto = { id: string; name: string; provider_type: string; office_ids: string[]; availability: AvailabilityWindowDto[]; exceptions: AvailabilityExceptionDto[]; archived: boolean }
export type ProviderScheduleEntry = { provider_id: string; provider_name: string; start_time: string; end_time: string }
/**
 * Returned from register_patient. Includes the new patient record and
 * an optional soft duplicate warning (does NOT block registration).
 */
export type RegisterPatientResult = { patient: PatientDto; duplicate_warning: string | null }
export type RescheduleAppointmentResult = { new_appointment_id: string }
export type SeedSummaryDto = { patients_created: number; providers_created: number; staff_created: number }
export type StaffMemberDto = { staff_member_id: string; name: string; phone: string | null; email: string | null; preferred_contact_channel: string | null; 
/**
 * True if the staff member has a PIN set (PIN hash itself is never exposed).
 */
has_pin: boolean; roles: string[]; archived: boolean }
/**
 * Returns whether the Staff Management setup step is complete.
 * Complete = at least one active PracticeManager has a PIN set.
 */
export type StaffSetupStatusDto = { complete: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
